# Generated by Django 5.1.7 on 2025-04-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du résultat')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('expected_value', models.FloatField(verbose_name='Valeur attendue')),
                ('tolerance', models.FloatField(default=0.0, help_text='Tolérance acceptée autour de la valeur attendue', verbose_name='Tolérance')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_results', to='biosim.experiment', verbose_name='Expérience')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_results', to='biosim.experimentvariable', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Résultat attendu',
                'verbose_name_plural': 'Résultats attendus',
                'ordering': ['experiment', 'variable__order', 'name'],
                'unique_together': {('experiment', 'variable')},
            },
        ),
    ]
