# Generated by Django 5.1.7 on 2025-04-04 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('theme', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='escape_rooms/covers/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='escape_rooms/backgrounds/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_escape_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escape Room',
                'verbose_name_plural': 'Escape Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('game_state', models.JSONField(default=dict)),
                ('escape_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='escapegame.escaperoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='escapegame.gamesession')),
            ],
            options={
                'verbose_name': 'Game Event',
                'verbose_name_plural': 'Game Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='escape_rooms/items/')),
                ('can_be_combined', models.BooleanField(default=False)),
                ('combination_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='escapegame.inventoryitem')),
                ('escape_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='escapegame.escaperoom')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='escape_rooms/rooms/')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('is_starting_room', models.BooleanField(default=False)),
                ('is_final_room', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('escape_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='escapegame.escaperoom')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('puzzle_type', models.CharField(choices=[('CODE', 'Code Entry'), ('SEQUENCE', 'Sequence Puzzle'), ('SWITCHES', 'Switches Puzzle'), ('TERMINAL', 'Terminal Puzzle'), ('ITEM_COMBINATION', 'Item Combination'), ('QUIZ', 'Quiz'), ('CUSTOM', 'Custom Puzzle')], max_length=20)),
                ('configuration', models.JSONField()),
                ('solution', models.JSONField()),
                ('hint_text', models.TextField(blank=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('educational_content', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='escapegame.room')),
            ],
            options={
                'verbose_name': 'Puzzle',
                'verbose_name_plural': 'Puzzles',
            },
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('reveal_condition', models.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='escapegame.inventoryitem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='escapegame.room')),
            ],
            options={
                'verbose_name': 'Item Location',
                'verbose_name_plural': 'Item Locations',
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_sessions', to='escapegame.room'),
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=True)),
                ('unlock_condition', models.JSONField(blank=True, null=True)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='escapegame.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='escapegame.room')),
            ],
            options={
                'verbose_name': 'Room Connection',
                'verbose_name_plural': 'Room Connections',
                'unique_together': {('from_room', 'to_room')},
            },
        ),
    ]
