# Generated by Django 4.2 on 2025-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_dialogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
